name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user/varun-devops-project
            git pull origin main

            docker stop varun-container || true
            docker rm varun-container || true
            docker rmi varun-app || true

            docker build -t varun-app .
            docker run -d -p 80:80 --name varun-container varun-app


             
